- LICENSE
- README.md
- example/src/App.js
- example/src/index.js
- package.json
- rollup.config.js
- src/index.js
- src/test.js
- yarn.lock
Added license, updated README & package.json.  Also added **prettier** as a dependency and precommit hook so all code is formatted nicely with a standard by default on commit.
> Configs and setup

- src/components/Button/Button.react.js
> Update Button component props.

- example/src/pages/400.react.js
- example/src/pages/401.react.js
- example/src/pages/403.react.js
- example/src/pages/404.react.js
- example/src/pages/500.react.js
- example/src/pages/503.react.js
- example/yarn.lock
- src/components/Alert/Alert.react.js
- src/components/Site/SiteFooter.js
- src/index.js
- src/page_templates/DefaultErrorPage.react.js
The great work that was done in #26 allows us to build a DefaultErrorPage component taking in a title, subtitle, and optional details.  This reduces code repetition and gives users an out of the box error page component.
This includes no UI changes, appearance should be identical.  I have attached a screenshot to confirm.
> Adding DefaultErrorPage component

- package.json
- src/components/Form/FormImageCheckItem.react.js
See `scripts/propscheck.py` for complete details on what it does
> Adding precommit hook to check for invalid/undesirable props.

- example/src/App.react.js
- example/src/interface/PricingCardsPage.react.js
- src/components/index.js
Real simple one, just uses the PricingCard components to build the the Pricing cards demo page
> Pricing cards demo page

- example/src/App.react.js
- example/src/interface/CardsDesignPage.react.js
Uses the new Card features to build the Cards design demo page
> Demo: adds CardsDesignPage

- example/src/FormElementsPage.react.js
- src/components/Form/Form.react.js
- src/components/Form/FormCheckbox.react.js
- src/components/Form/FormInput.react.js
- src/components/Form/FormRadio.react.js
- src/components/Form/FormSelectGroup.react.js
- src/components/Form/FormSelectGroupItem.react.js
Adds new components for radio/checkbox button select groups and adds them to the demo page
> Form input select button groups

- example/src/FormElementsPage.react.js
- src/components/Form/Form.react.js
- src/components/Form/FormFieldSet.react.js
- src/components/Form/FormGroup.react.js
Adds new Form.FieldSet component and gives Form.Group a new prop, isRequired, which adds an * to the fields label
> Adds Form.FieldSet

- .gitignore
- example/src/interface/CardsDesignPage.react.js
- src/components/Card/Card.react.js
- src/components/Card/CardFooter.react.js
> CardFooter

- example/src/App.react.js
- example/src/documentation/DocsAvatarsPage.react.js
- example/src/documentation/index.js
> Adds Avatar docs page

- example/src/App.react.js
- example/src/documentation/DocsButtonsPage.react.js
- example/src/documentation/index.js
- src/components/Dropdown/DropdownTrigger.react.js
> Buttons docs page

- example/src/ComponentDemo/ComponentDemo.react.js
- example/src/FormElementsPage.react.js
- example/src/pages/Email.react.js
- src/components/Button/Button.react.js
- src/page_templates/DefaultErrorPage.react.js
Tried to make clearer the Button internal workings and types
> Rearrange button internals

- example/src/App.react.js
- example/src/documentation/DocsTagsPage.react.js
- example/src/documentation/index.js
- src/components/Tag/Tag.react.js
- src/components/Tag/TagAddOn.react.js
- src/components/Tag/TagList.react.js
- src/components/Tag/index.js
- src/components/index.js
> Adds tags components

- example/src/documentation/DocsCardsPage.react.js
- example/src/interface/CardsDesignPage.react.js
- src/components/Dimmer/Dimmer.react.js
- src/components/Dimmer/DimmerContent.react.js
- src/components/Dimmer/index.js
- src/components/Loader/Loader.react.js
- src/components/Loader/index.js
- src/components/index.js
> Adds Dimmer and Loader components

- src/components/Stamp/Stamp.react.js
- src/components/Stamp/index.js
- src/components/StampCard/StampCard.react.js
- src/components/index.js
> Adds Stamp component

- src/components/Text/Text.react.js
> Adds muted prop to Text componenent

- src/components/List/List.react.js
> Gives the List component a new 'seperated' prop

- src/components/Badge/Badge.react.js
> Adds color prop to Badge

- src/components/Table/Table.react.js
- src/components/Table/TableCol.react.js
- src/components/Table/TableColHeader.react.js
Adds highlightRowOnHover, hasOutline and verticalAlign props to Table
Adds alignContent props to Table.Col and Table.ColHeader
> Additional table props

- src/components/Text/Text.react.js
- src/components/Text/TextSmall.react.js
Adds a new Text.Small component for rendering <small> text components
> Adds Text.Small component

- src/components/ProgressCard/ProgressCard.react.js
- src/components/ProgressCard/index.js
> Adds ProgressCard

- example/src/HomePage.react.js
This will bring our demo homepage in line with the [tabler site](https://tabler.github.io/tabler/index.html) but it requires most, if not all of the outstanding PRs before this can be merged.
> WIP: Update demo home page to closer match tabler demo

- example/src/FormElementsPage.react.js
- src/components/Form/Form.react.js
- src/components/Form/FormInputGroup.react.js
- src/components/Form/FormInputGroupAppend.react.js
- src/components/Form/FormInputGroupPrepend.react.js
> Adds InputGroupAppend and Prepend + demos

- src/components/StatsCard/StatsCard.react.js
- src/components/StatsCard/index.js
- src/components/index.js
> Adds StatsCard

- src/components/PricingCard/PricingCardButton.react.js
I added these props to make functionality to this component, We can add these changes into this version, do for another version or implement better logic, the choice is yours.
> PricingCardButton:Added href,to,onClick props, Updated component logic

- example/src/App.react.js
- example/src/GalleryPage.react.js
- example/src/data/Gallery.Items.json
- src/components/index.js
For the other elements that are placed on the **Page Header**, some modifies may be required on **Page.Header** Component, When I attempt to add another component to **Page.Header**, It has combined with elements under the **Page Title** div , not under the Page.Header
> Gallery demo page

- example/src/App.react.js
- example/src/documentation/DocsIntroPage.react.js
- example/src/documentation/DocsTypographyPage.react.js
- example/src/documentation/index.js
- src/components/Text/Text.react.js
> Typography documentation

- src/components/GalleryCard/GalleryCardIconItem.react.js
Fix for the belowing issue
[#116](https://github.com/tabler/tabler-react/issues/116)
> Fixed prop type declaration

- scripts/propscheck.py
Add exceptions to props checking.
This resolves #116
> Add Exceptions to props checking script

- example/src/SiteWrapper.react.js
- example/src/components/StoreCardsPage.react.js
- example/src/documentation/DocsColorsPage.react.js
- example/src/documentation/DocsFormComponentsPage.react.js
- example/src/documentation/DocsIntroPage.react.js
- example/src/interface/ChartsPage.react.js
- src/components/StoreCard/StoreCard.react.js
Resolves #123 .  Should now see `Compiled successfully!` when running the demo instead of a bunch of warnings.
> Remove all compilation warnings

- example/src/FormElementsPage.react.js
- example/src/GalleryPage.react.js
- src/components/Dropdown/Dropdown.react.js
- src/components/Form/FormGroup.react.js
- src/components/Page/PageOptions.react.js
- src/components/Page/PageSubTitle.react.js
I have tried to fix some errors that I encountered
> Quick fixes

- src/components/Text/Text.react.js
> Fix: Text should default to a <div> instead of <p>

- example/src/App.react.js
- example/src/ComponentDemo/ComponentDemo.react.js
- example/src/SiteWrapper.react.js
- example/src/documentation/DocsBadgePage.react.js
- example/src/documentation/DocsDropdownPage.react.js
- example/src/documentation/DocsGridPage.react.js
- example/src/documentation/DocsListPage.react.js
- example/src/documentation/DocsNavPage.react.js
- example/src/documentation/DocsSidebar.react.js
- example/src/documentation/DocsStampPage.react.js
- example/src/documentation/DocsTablePage.react.js
- example/src/documentation/index.js
- src/components/Dropdown/Dropdown.react.js
- src/components/Dropdown/DropdownItem.react.js
- src/components/Dropdown/DropdownTrigger.react.js
- src/components/Nav/NavItem.react.js
@AaronCoplan this is some work I was doing before the new documentation system but it also fixes some small bits and pieces that were missing/not working as expected that I need for the new docs, nothing really to review and most of the docs stuff will be removed soon ;)
> Missing component documentation pages

- .flowconfig
- example/src/HomePage.react.js
- package.json
- src/components/Table/Table.css
- src/components/Table/Table.react.js
- yarn.lock
This fixes #136 by removing the className causing overflow to be hidden. Also removes the arrow toggle next to the icon.
> Remove additional className from the Card.Body and hide the toggle arrow

- example/src/components/IconPage.react.js
> [example IconPage]: Did not render &lg; and &gt; correctly

- example/src/HomePage.react.js
- example/src/SiteWrapper.react.js
Fixes the home page and nav bar documentation links
> Fix the links to documentation

- package.json
- yarn.lock
This adds a missing dependency to package.json for fixing the flow .css import issues we experienced.
> Adds missing dependency for fixing flow related .css import issues

- src/components/Alert/Alert.react.js
Removes the jQuery data attribute based hiding of Alerts and replaces it with state/onClick. Also provides a onDismissClick prop.
> Alert: Replaces jQuery based dismissing with state and onClick

- src/components/Notification/Notification.examples.md
- src/components/Notification/Notification.react.js
- src/components/Notification/NotificationTray.examples.md
- src/components/Notification/NotificationTray.react.js
- src/components/Notification/index.js
- src/components/index.js
- styleguide.config.js
Extracts the Notification dropdown from the SiteWrapper and turns it into it's own set of reusable components
> Add Notification and NotificationTray

- package.json
- yarn.lock
> chore(package): Update flow-bin to 0.71.0

- example/src/FormElementsPage.react.js
- src/components/Button/Button.examples.md
- src/components/Button/Button.react.js
- src/components/Button/ButtonDropdown.examples.md
- src/components/Button/ButtonDropdown.react.js
- src/components/Dropdown/Dropdown.react.js
- src/components/Dropdown/DropdownMenu.react.js
- src/components/Dropdown/DropdownTrigger.react.js
This adds a ButtonDropdown component, a Button that when clicked displays a DropdownMenu
> ButtonDropdown

- src/components/Button/ButtonDropdown.react.js
- src/components/Form/FormTextarea.react.js
- yarn.lock
This resolves #167 .  Also encountered flow issue (see attached screenshot) - so resolved that as well.
> Textarea onchange and fix flow problem

- example/src/SiteWrapper.react.js
- src/components/Site/SiteHeader.react.js
Adds a new navItems prop to SiteHeader to pass through any nav items to display
Fixes #174
> fix(Site): Remove tabler-react source code button from SiteHeader

- src/components/Dropdown/Dropdown.react.js
- src/components/Nav/NavItem.react.js
- src/helpers/ClickOutside.react.js
Creates a new ClickOutside helper component and uses it in Dropdown and NavItem
Fixes #165
> fix(Dropdown): Fix Dropdown should when user clicks outside of it

- example/src/pages/400.react.js
- example/src/pages/401.react.js
- example/src/pages/403.react.js
- example/src/pages/404.react.js
- example/src/pages/500.react.js
- example/src/pages/503.react.js
- src/index.js
- src/page_templates/errors/DefaultErrorPage.react.js
- src/page_templates/errors/Error400Page.react.js
- src/page_templates/errors/Error401Page.react.js
- src/page_templates/errors/Error403Page.react.js
- src/page_templates/errors/Error404Page.react.js
- src/page_templates/errors/Error500Page.react.js
- src/page_templates/errors/Error503Page.react.js
- styleguide.config.js
This takes the error pages from the example site and turns them into tabler-react components that you can import for even quicker creation of your error pages.
> Error pages

- example/src/SiteWrapper.react.js
- src/components/Site/SiteFooter.react.js
- src/components/Site/SiteWrapper.react.js
Adds props to SiteFooter to make it usable just like all our other components.
Resolves #177, #174
> feat(SiteFooter): Make the SiteFooter content editable via props

- src/components/Form/Form.react.js
- src/components/Form/FormInput.react.js
- src/forms/FormCard.react.js
- src/forms/FormTextInput.react.js
Adds onSubmit, onChange, onBlur props where they were missing on various Form components
> Form events props

- package.json
> chore(package): update rollup to version 0.59.3

- package.json
> chore(package): update rollup to version 0.60.2

- example/src/SiteWrapper.react.js
> docs(): wrap react router NavLinks in withRouter

- src/components/Form/Form.react.js
- src/components/Form/FormCheckbox.react.js
- src/components/Form/FormColorCheckItem.react.js
- src/components/Form/FormFileInput.react.js
- src/components/Form/FormImageCheckItem.react.js
- src/components/Form/FormInput.react.js
- src/components/Form/FormLabel.react.js
- src/components/Form/FormMaskedInput.react.js
- src/components/Form/FormRadio.react.js
- src/components/Form/FormRatio.react.js
- src/components/Form/FormSelect.react.js
- src/components/Form/FormSelectGroup.react.js
- src/components/Form/FormSelectGroupItem.react.js
- src/components/Form/FormStaticText.react.js
- src/components/Form/FormSwitch.react.js
- src/components/Form/FormTextarea.react.js
- src/flow/events/Form.flow.js
- src/page_templates/account/ForgotPasswordPage/ForgotPasswordPage.react.js
- src/page_templates/account/LoginPage/LoginPage.react.js
- src/page_templates/account/RegisterPage/RegisterPage.react.js
This PR is to address missing event handling in Form Components.
Most vital components have been updated with the following events handlers:
- onClick
- onChange
- onMouseEnter
- onMouseLeave
- onPointerEnter
- onPointerLeave
- onBlur
- onFocus
Some also have onSubmit depending on their need.
> Add Form component event handling

- example/package.json
- example/src/App.react.js
- example/yarn.lock
- src/components/Site/SiteHeader.react.js
- src/components/Site/SiteNav.react.js
- src/components/Site/SiteWrapper.react.js
> Remove bootstrap dependencies from example site and fix mobile collapsing menu button

- src/Tabler.css
- src/components/Container.css
- src/components/Container.react.js
- src/components/Site/SiteHeader.react.js
This PR resolves issue #259 
Add an alignment tag for header content to the center of the page and Container capability to receive className prop
>  feat(*): Add SiteHeader center alignment capability 

- src/components/Table/Table.css
- src/components/Table/Table.react.js
I removed the css file and the import so it stops overriding the default style. #263
> the responsive layout should come from the main bootstrap theme

- src/components/Grid/GridCol.examples.md
- src/components/Grid/GridCol.react.js
> feat(GridCol): add offset props

- example/src/App.react.js
- example/src/components/BlogPage.react.js
- src/Tabler.css
This resolves #72 by adding a demo page.
Fixes a missing `flex` attribute in the CSS, which is present in the RTL version and on the Tabler Website.
Did some code clean-up in `App.react.js`
> Add Blog Demo Page

- example/package.json
> fix(package): update formik to version 1.0.2

- example/package.json
> fix(package): update react-syntax-highlighter to version 8.0.1

- package.json
> chore(package): update @semantic-release/git to version 7.0.1

- package.json
> chore(package): update eslint-plugin-jsx-a11y to version 6.1.1

- example/src/App.react.js
- example/src/HomePage.react.js
- example/src/components/BlogPage.react.js
- example/src/documentation/DocsTablePage.react.js
- scripts/runflow
- src/components/Table/Table.react.js
Resolves #307 .  Adds key to Table component and updates relevant code that uses that shorthand.
> Table body items key

- example/src/HomePage.react.js
- src/components/Dropdown/Dropdown.react.js
Working on getting dropdowns on demo home page to work correctly.
> Updating dropdowns to work properly with shorthand notation.

- example/src/SiteWrapper.react.js
- src/components/Nav/Nav.react.js
- src/components/Nav/NavItem.react.js
- src/components/Site/SiteNav.react.js
- src/components/Site/SiteWrapper.react.js
- src/helpers/RouterContextProvider.react.js
- src/index.js
> fix(Dropdown): Highlight menu dropdown when underlying component selected

- package.json
- src/components/Tooltip/Tooltip.react.js
Adding `show` as a constant class seems to have resolved the issue.
> Tooltip fix

- package.json
- yarn.lock
Aggregated changes from old Greenkeeper PRs and resolved merge conflicts.  Packages updated are as follows:
* commitizen
* webpack
* eslint-config-react-app
* eslint-plugin-flowtype
This will close several Greenkeeper PRs as it replaces them.
> Greenkeeper PR Changes

- package.json
- yarn.lock
Reverts tabler/tabler-react#363
> Revert "Update webpack to the latest version 🚀"

- src/Tabler.RTL.css
- src/Tabler.css
It should fix select's caret display on Firefox
See #364
> fix(Select): escape '#' on URI

- src/components/Form/Form.react.js
This PR replaces #368, which I have closed per recommendations on #289.  I only added the auto complete property to **Form**, I thought it might be best to implement field specific auto complete in a future PR, but I am open to discussion.
@GregoryHamel If you have any thoughts / review that would be awesome!
> Setting up autocomplete in Form

- src/page_templates/errors/DefaultErrorPage.react.js
- src/page_templates/errors/Error400Page.react.js
- src/page_templates/errors/Error401Page.react.js
- src/page_templates/errors/Error403Page.react.js
- src/page_templates/errors/Error404Page.react.js
- src/page_templates/errors/Error500Page.react.js
- src/page_templates/errors/Error503Page.react.js
https://github.com/tabler/tabler-react/issues/395
Added `action` prop to the error page templates to change the button's text.
> Error Page Action

- src/components/Grid/GridRow.react.js
https://getbootstrap.com/docs/4.0/layout/grid/#horizontal-alignment
> justify-content

- src/components/AccountDropdown/AccountDropdown.react.js
> Make the avatarURL optional in the AccountDropdown

- src/page_templates/StandaloneFormPage.react.js
- src/page_templates/account/ForgotPasswordPage/ForgotPasswordPage.react.js
- src/page_templates/account/LoginPage/LoginPage.react.js
- src/page_templates/account/RegisterPage/RegisterPage.react.js
Made the logo variable by passing it in LoginPage/RegisterPage/ForgotPasswordPage
> feat(StandAloneFormPage): Made the logo variable

- package-lock.json
- package.json
> Greenkeeper/rollup 1.13.0

- package-lock.json
- package.json
> Greenkeeper/rollup plugin node resolve 5.0.1

- package-lock.json
- package.json
> Greenkeeper/prettier 1.17.1

- example/src/SiteWrapper.react.js
- src/components/Dropdown/DropdownItem.react.js
- src/components/Nav/Nav.react.js
- src/components/Nav/NavItem.react.js
- src/components/Nav/NavSubItem.react.js
- src/components/Site/SiteNav.react.js
https://github.com/tabler/tabler-react/issues/407
I'm not sure if this is the best solution because of the additional prop added to the `Dropdown.Item`, so feedback would be appreciated!
> useExact for subNavItems
