tabler/tabler-react

- package.json
This addresses #2, but should not be merged until #6 is because that PR cleans up the existing use of prop-types.  At that point, running `flow` will verify that this will not break anything.
> Removing prop-types from package.json.

- src/components/Form/FormInput.react.js
- src/forms/FormCheckboxInput.react.js
- src/forms/FormTextInput.react.js
The `FormInput` component alone is kind of abstract and hard to use - it also has a ton of properties.  Thus, I've added two out of the box solutions for this - one is `FormCheckboxInput` (self explanatory), the other is `FormTextInput`, used for email, password, text, number, etc (anything that can be represented by text).  These are useful out of the box form inputs that track state and people can use instead of the base `FormInput` component.
> Refactor form input components to use basic components.

- example/src/HomePage.react.js
- src/components/Table/Table.react.js
Adds Tabler headerItems and bodyItems shorthand props
Example:
```jsx
<Table
headerItems={[
{ content: "Name", className: "w-1" },
{ content: "Action" },
]}
bodyItems={[
[
{
content: 'Jon',
},
{
alignContent: 'right',
content: <Button>Action</Button>
}
]
]}
/>
```
> Table shorthand props

- example/src/GalleryPage.react.js
- example/src/HomePage.react.js
- example/src/components/StoreCardsPage.react.js
- example/src/documentation/DocsPageWrapper.react.js
- example/src/interface/PricingCardsPage.react.js
- src/components/Page/PageContent.react.js
- src/components/Page/PageHeader.react.js
- src/components/Page/PageOptions.react.js
- src/components/Page/PageSubTitle.react.js
Adds title, subTitle and options props to Page.Header and Page.Content for props based building of page header.
Example:
```jsx
<Page.Content title='Hello' subTitle='World' options={<Button>Something</Button>} />
```
> Page header shorthand props

- example/src/documentation/DocsButtonsPage.react.js
- src/components/Button/Button.react.js
https://tabler.github.io/tabler-react/docs/buttons currently throws an error
```
input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
```
> fix(Button): inputs cannot have children

- package.json
- scripts/runflow
This adds a precommit hook for flow.  Script checks for npm or yarn then uses the appropriate one to run flow.  Precommit will fail if flow has exit code of anything but zero or if neither npm nor yarn provide flow.
We could run this on specific files using the `flow force-recheck filename1 filename2 ...` command, but might as well check to make sure no files have errors by just running `flow`.  Let me know your thoughts on this @jonthomp 
This resolves #115
> Adding precommit hook for flow

- src/components/Tabs/Tabs.css
- src/components/Tabs/Tabs.react.js
This moves the inline style for adding some space below the tabs, into a separate Tab.css file.
To make sure CSS modules hashed classNames are always being attached to their components, we need to use this method for adding className strings into props:
Use a named import which turns the classNames into a js object we can use:
```js
import styles from './ComponentStyles.css';
```
In ComponentStyles.css:
```css
.margin-bottom-24 {
margin-bottom: 24px !important;
}
```
Then we can use template literals to make sure the component receives the correct hashed className:
```jsx
className={`someClassName ${styles["margin-bottom-24"]}`}
```
Or using classnames library:
```jsx
const classes = cn(styles["margin-bottom-24"], 'someClassName');
```
> Moves inline style to Tabs.css

- example/yarn.lock
- src/components/Dropdown/Dropdown.react.js
- src/components/Dropdown/DropdownMenu.react.js
- src/components/Dropdown/DropdownTrigger.react.js
- src/components/Nav/NavItem.react.js
- src/components/Nav/NavLink.react.js
This uses react-popper for the positioning of the `Dropdown`s created for `NavItem` subnav items.
In order to help with this, the `Reference` and `Popper` components within `Dropdown` have been moved into `Dropdown.Trigger` and `Dropdown.Menu`
> NavItem subnav Dropdown positioning

- src/components/AccountDropdown/AccountDropdown.examples.md
- src/components/AccountDropdown/AccountDropdown.react.js
- src/components/AccountDropdown/index.js
- src/components/Dropdown/Dropdown.react.js
- src/components/index.js
- styleguide.config.js
Adds a component for easily replicating the Avatar/user dropdown seen in the top right hand corner of the demo website.
Also adds a new prop to `Dropdown` to allow setting of the default RootComponent to be used with `DropdownItem`s generated from the `itemsObject` prop.
> Add AccountDropdown

- example/src/SiteWrapper.react.js
- src/components/AccountDropdown/AccountDropdown.react.js
- src/components/Form/FormMaskedInput.react.js
- src/components/Notification/NotificationTray.react.js
- src/components/Site/Site.react.js
- src/components/Site/SiteHeader.react.js
- src/components/Site/SiteLogo.react.js
- src/components/Site/SiteNav.react.js
- src/components/Site/SiteWrapper.react.js
This takes the SiteWrapper component used in the example site and creates a reusable Site.Wrapper tabler-react component. In addition, SiteHeader and SiteNav both gain new shorthand hand props.
Other bits and pieces:
- FormMaskedInput fixed type issue
- AccountDropdown and Notification prop types are now exported
> SiteWrapper

- package.json
Fixes the issue mentioned in #114 by adding a copytablercsstodist script to package and running it before the build and start scripts
> fix(tabler css): copy tabler css before build and start

- src/components/Icon/Icon.examples.md
- src/components/Icon/Icon.react.js
- styleguide.config.js
Some small amends and docs improvements for Icons
- This updates the Icon docs to include font awesome instructions and flow type comments
- remove strict types on the Icon prefix prop
- Also adds a new `flag` prop that does exactly the same as the `payment` prop but for flags
- updates styleguide config so it loads fontawesome icons and google fonts
> Icon docs and minor amends

- src/components/Dropdown/DropdownMenu.react.js
Removes the callto scheduleUpdate and only renders the Popper if show
prop is true
Fixes #228
> fix(DropdownMenu): performance issue 228

- src/components/Tooltip/Tooltip.react.js
Placement needs to be imported as a type. This fixes the non-existant import error during build.
> fix(Tooltip): Fix non-existant Placement import

- package.json
I attempted to fix this in #235 but apparently made a mistake in the package.json scripts section. This PR causes the custom `flow-copy-source` script to actually run, fixing the original problem.
> fix(): Actually run custom flow-copy-source script on build

- src/components/Nav/NavItem.react.js
fix #226 by making `NavItem` extend Component instead of PureComponent
> fix(NavItem): extend Component

- src/components/Table/TableCol.react.js
Table.Col is missing colSpan property, so I added it.
> feat(): added colSpan to Table.Col (as in Table.ColHeader)

- src/components/Grid/GridCol.react.js
- src/components/Site/SiteNav.react.js
Resolves #302 .  Adds a simple property to ignore the `col` CSS class and uses it in **SiteNav** component..
> fix(SiteNav): Fix misaligned menu for mobile / smaller screens.

- package.json
Add SHX dependency to allow posix-only command such as `rm` and `cp` to be called in the build
process for win32 environments.
fix #347
> fix(package): Fix win32 build error caused by posix-only command

- example/src/SiteWrapper.react.js
- src/components/Notification/NotificationTray.react.js
This pull request adds the ability to provide a callback so the application can resolve unread notifications when the 'mark all as read' button is clicked.
As part of this implementation the 'mark all as read' button is removed if there are no unread messages.
Demo application was updated to show unread notifications on start, then when the 'mark all read' button is activated, sets the flag to set unread to false, and then sets a timeout for 5 seconds to set unread to true again.
> Notification tray mark all as read implementation

- src/components/Form/FormInput.react.js
Adds autoFocus prop to the FormInput component 👍😎
> feat(FormInput): add autoFocus to FormInput

- example/src/SiteWrapper.react.js
- src/components/Notification/Notification.react.js
- src/components/Notification/NotificationTray.react.js
- src/components/Notification/index.js
- src/components/index.js
- src/index.js
Adds some background styling when showing unread notifications in the notifications tray
See https://github.com/tabler/tabler-react/issues/376 for conversation around this pull request.
> feat(NotificationTray): Style the unread notifications

- example/src/SiteWrapper.react.js
- src/components/Nav/Nav.react.js
- src/components/Nav/NavItem.react.js
- src/components/Nav/NavLink.react.js
- src/components/Site/SiteNav.react.js
Fixing NavLink state per recommendation in #361 .  Seems to work for the example - @GregoryHamel thoughts on this?
This resolves #361
> fix(NavLink): Fixed navlink active state.

- example/src/FormElementsPage.react.js
- src/components/Form/Form.react.js
- src/components/Form/FormInputGroupText.react.js
Added the following as a component, named `InputGroupText` and added it to the `InputGroupPrepend` and `InputGroupAppend` demos to fix a display bug:
`<span class="input-group-text">...</span>`
https://i.gyazo.com/cf794a25e70397acb4239ced1196e94c.png
https://i.gyazo.com/9e1a59bc7aa688dcf07d42a330fa016c.png
> Form.InputGroupText

- src/components/Button/Button.react.js
This PR adds the tabIndex property to the Button component. This allows for making buttons which can be ignored when tabbing to focus elements.
The GIF below demonstrates a button which can be focused by default by tabbing to it, however when it is given a tabIndex of "-1" it can no longer be highlighted by tabbing to it.
> feat(Button): add tabIndex property

- src/components/Form/FormFileInput.react.js
Added support for ["accept" property of input[type=file]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept) in FileInput
Related Issue: [#418](https://github.com/tabler/tabler-react/issues/418)
> feat(FileInput): add accept property

- src/Tabler.css
This will fix this eslint warning 
```
Compiled with warnings.
./node_modules/tabler-react/dist/Tabler.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/tabler-react/dist/Tabler.css)
Warning
(9939:3) Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed
Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip
> fix(text-decoration-skip) - Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

- src/components/Table/TableHeader.examples.md
I found that the docs were missing a <Table.Row> declaration, which led to warnings on my dev server during compile. I've added these and hopefully you can just pull into the repo to help others.
> Edit to <Table.Header> example

- src/page_templates/account/LoginPage/LoginPage.react.js
The LoginPage logo should be set by a prop. It should not be the demo logo.
> Remove demo imageURL for LoginPage
